---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mosquitto:
        image: eclipse-mosquitto:1.6
        ports:
          - 1883/tcp
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Run unit tests
        run: go test -v -cover -race
        env:
          TEST_MQTT_ADDR: 127.0.0.1:${{ job.services.mosquitto.ports['1883'] }}
